version: "3.5"
services:
  depker-server:
    build:
      context: .
    container_name: depker-server
    volumes:
      - ~/.config/depker:/root/.config/depker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
