version: "3.9"
services:
  traefik:
    image: traefik:latest
    command:
      - --configFile=/var/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/var/traefik
networks:
  default:
    name: docker
# docker network create docker
